- name: 'nginx | install packages'
  apt:
    pkg:
      - 'nginx'
  tags: 'nginx'

- name: 'nginx | disable default config'
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: 'nginx | copy config'
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/{{ project_name }}.conf owner=root group=root
  tags: 'nginx'

- name: 'nginx | restart nginx'
  service: name=nginx state=restarted enabled=yes
  tags: 'nginx'