- name: 'dependencies | install core packages'
  apt:
    update_cache: yes

- name: 'apt | install dependencies'
  apt:
    pkg:
  #    - 'autoconf'
  #    - 'bison'
  #    - 'libyaml-dev'
  #    - 'libreadline6-dev'
  #    - 'libncurses5-dev'
  #    - 'libmagickwand-dev'
  #    - 'libcurl4-openssl-dev'
  #    - 'libffi-dev'
  #    - 'libgdbm3'
  #    - 'libgdbm-dev'
  #    - 'redis-server'
  #    - 'python-psycopg2'
  #    - 'libpq-dev'
      - 'build-essential'
      - 'libssl-dev'
      - 'zlib1g-dev'
      - 'imagemagick'
      - 'htop'
      - 'curl'
      - 'vim'
      - 'git'
  tags: 'dependencies'

- name: 'dependencies | create deploy account'
  user: 'name={{ user }} shell=/bin/bash'
  tags: 'dependencies'

- name: 'dependencies | copy authorized keys to deploy account'
  shell: 'mkdir -p {{home}}/.ssh -m 700 && cp /root/.ssh/authorized_keys {{home}}/.ssh && chown -R {{user}}:{{user}} {{home}}/.ssh'
  tags: 'dependencies'