- name: 'apt | update'
  action: 'apt update_cache=yes'
  tags: 'dependencies'

- name: 'apt | install dependencies'
  action: 'apt pkg={{ item }}'
  with_items:
    - 'autoconf'
    - 'bison'
    - 'build-essential'
    - 'libssl-dev'
    - 'libyaml-dev'
    - 'libreadline6-dev'
    - 'libncurses5-dev'
    - 'libmagickwand-dev'
    - 'libcurl4-openssl-dev'
    - 'libffi-dev'
    - 'libgdbm3'
    - 'libgdbm-dev'
    - 'zlib1g-dev'
    - 'git'
    - 'nginx'
    - 'redis-server'
    - 'postgresql'
    - 'postgresql-contrib'
    - 'python-psycopg2'
    - 'libpq-dev'
    - 'imagemagick'
    - 'nodejs'
    - 'htop'
    - 'curl'
  tags: 'dependencies'

- name: 'account | create'
  user: 'name={{ user }} shell=/bin/bash'
  tags: 'dependencies'

- name: 'account | copy authorized keys'
  shell: 'mkdir -p {{ home }}/.ssh -m 700 && cp /root/.ssh/authorized_keys {{ home }}/.ssh && chown -R {{ user }}:{{ user }} {{ home }}/.ssh'
  tags: 'dependencies'
