- name: 'postgres | install packages'
  apt:
    pkg:
      - 'postgresql'
      - 'postgresql-contrib'
      - 'python3-psycopg2'
      - 'libpq-dev'
      - 'python-psycopg2'
  tags: 'postgres'

- name: 'postgres | restart pg'
  systemd:
    name: postgresql
    state: started
    enabled: yes
  tags: 'postgres'

- name: 'postgres | create the postgresql user for application'
  postgresql_user: name={{ db_user }} password={{ db_password }} role_attr_flags=CREATEDB,NOSUPERUSER
  become: yes
  become_user: postgres
  tags: 'postgres'

- name: 'postgres | create the postgresql database for application'
  postgresql_db: name={{ db_name }} owner={{ db_user }} encoding={{ db_encoding }} state=present
  become: yes
  become_user: postgres
  tags: 'postgres'

- name: 'postgresql | make shared dir'
  become: yes
  become_user: '{{user}}'
  file: path={{project_root}}/shared/config state=directory
  tags: 'postgres'


- name: 'postgresql | copy database.yml'
  template: 'src=database.yml dest={{ project_root }}/shared/config/database.yml mode=0644'
  become: yes
  become_user: '{{user}}'
  tags: 'postgres'
