- name: 'ruby | clone rbenv repo'
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/rbenv/rbenv.git dest={{ rbenv_root }}
  tags: 'ruby'

- name: 'ruby | export rbenv path'
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: "{{home}}/.bashrc"
    state: present
    line: 'export PATH="${HOME}/.rbenv/bin:${PATH}"'
  tags: 'ruby'

- name: 'ruby | export rbenv path'
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: "{{home}}/.bashrc"
    state: present
    line: 'eval "$(rbenv init -)"'
  tags: 'ruby'

- name: 'ruby | install ruby build'
  become: yes
  become_user: "{{ user }}"
  git: repo=https://github.com/rbenv/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build
  tags: 'ruby'

- name: 'ruby | install ruby'
  become: yes
  become_user: "{{ user }}"
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv install {{ ruby_version }} --skip-existing'
  tags: 'ruby'


- name: 'ruby  | set global ruby {{ ruby_version }}'
  become: yes
  become_user: "{{ user }}"
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv global {{ ruby_version }}'
  tags: 'ruby'

- name: 'ruby  | rbenv rehash'
  become: yes
  become_user: "{{ user }}"
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv rehash'
  tags: 'ruby'

- name: 'ruby | install bundler'
  become: yes
  become_user: "{{ user }}"
  shell: 'RBENV_ROOT={{ rbenv_root }} PATH="$RBENV_ROOT/bin:$PATH" rbenv exec gem install bundler'
  tags: 'ruby'